// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"demo3/internal/dao/internal"
)

// internalActivityCommentDao is internal type for wrapping internal DAO implements.
type internalActivityCommentDao = *internal.ActivityCommentDao

// activityCommentDao is the data access object for table activity_comment.
// You can define custom methods on it to extend its functionality as you wish.
type activityCommentDao struct {
	internalActivityCommentDao
}

var (
	// ActivityComment is globally public accessible object for table activity_comment operations.
	ActivityComment = activityCommentDao{
		internal.NewActivityCommentDao(),
	}
)

// Fill with you ideas below.
