// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"demo3/internal/dao/internal"
)

// internalActivityInfoDao is internal type for wrapping internal DAO implements.
type internalActivityInfoDao = *internal.ActivityInfoDao

// activityInfoDao is the data access object for table activity_info.
// You can define custom methods on it to extend its functionality as you wish.
type activityInfoDao struct {
	internalActivityInfoDao
}

var (
	// ActivityInfo is globally public accessible object for table activity_info operations.
	ActivityInfo = activityInfoDao{
		internal.NewActivityInfoDao(),
	}
)

// Fill with you ideas below.
