// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"demo3/internal/dao/internal"
)

// internalActiveOrderDao is internal type for wrapping internal DAO implements.
type internalActiveOrderDao = *internal.ActiveOrderDao

// activeOrderDao is the data access object for table active_order.
// You can define custom methods on it to extend its functionality as you wish.
type activeOrderDao struct {
	internalActiveOrderDao
}

var (
	// ActiveOrder is globally public accessible object for table active_order operations.
	ActiveOrder = activeOrderDao{
		internal.NewActiveOrderDao(),
	}
)

// Fill with you ideas below.
