// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"demo3/internal/dao/internal"
)

// internalActivityViewContextDao is internal type for wrapping internal DAO implements.
type internalActivityViewContextDao = *internal.ActivityViewContextDao

// activityViewContextDao is the data access object for table activity_view_context.
// You can define custom methods on it to extend its functionality as you wish.
type activityViewContextDao struct {
	internalActivityViewContextDao
}

var (
	// ActivityViewContext is globally public accessible object for table activity_view_context operations.
	ActivityViewContext = activityViewContextDao{
		internal.NewActivityViewContextDao(),
	}
)

// Fill with you ideas below.
