// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"demo3/internal/dao/internal"
)

// internalActivityContextDao is internal type for wrapping internal DAO implements.
type internalActivityContextDao = *internal.ActivityContextDao

// activityContextDao is the data access object for table activity_context.
// You can define custom methods on it to extend its functionality as you wish.
type activityContextDao struct {
	internalActivityContextDao
}

var (
	// ActivityContext is globally public accessible object for table activity_context operations.
	ActivityContext = activityContextDao{
		internal.NewActivityContextDao(),
	}
)

// Fill with you ideas below.
