// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"demo3/internal/dao/internal"
)

// internalBelongschoolInfoDao is internal type for wrapping internal DAO implements.
type internalBelongschoolInfoDao = *internal.BelongschoolInfoDao

// belongschoolInfoDao is the data access object for table belongschool_info.
// You can define custom methods on it to extend its functionality as you wish.
type belongschoolInfoDao struct {
	internalBelongschoolInfoDao
}

var (
	// BelongschoolInfo is globally public accessible object for table belongschool_info operations.
	BelongschoolInfo = belongschoolInfoDao{
		internal.NewBelongschoolInfoDao(),
	}
)

// Fill with you ideas below.
