// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"demo3/internal/dao/internal"
)

// internalEmployeeIsOnDao is internal type for wrapping internal DAO implements.
type internalEmployeeIsOnDao = *internal.EmployeeIsOnDao

// employeeIsOnDao is the data access object for table employee_is_on.
// You can define custom methods on it to extend its functionality as you wish.
type employeeIsOnDao struct {
	internalEmployeeIsOnDao
}

var (
	// EmployeeIsOn is globally public accessible object for table employee_is_on operations.
	EmployeeIsOn = employeeIsOnDao{
		internal.NewEmployeeIsOnDao(),
	}
)

// Fill with you ideas below.
