// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"demo3/internal/dao/internal"
)

// internalSchoolInfoDao is internal type for wrapping internal DAO implements.
type internalSchoolInfoDao = *internal.SchoolInfoDao

// schoolInfoDao is the data access object for table school_info.
// You can define custom methods on it to extend its functionality as you wish.
type schoolInfoDao struct {
	internalSchoolInfoDao
}

var (
	// SchoolInfo is globally public accessible object for table school_info operations.
	SchoolInfo = schoolInfoDao{
		internal.NewSchoolInfoDao(),
	}
)

// Fill with you ideas below.
