// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"demo3/internal/dao/internal"
)

// internalStudentInfoDao is internal type for wrapping internal DAO implements.
type internalStudentInfoDao = *internal.StudentInfoDao

// studentInfoDao is the data access object for table student_info.
// You can define custom methods on it to extend its functionality as you wish.
type studentInfoDao struct {
	internalStudentInfoDao
}

var (
	// StudentInfo is globally public accessible object for table student_info operations.
	StudentInfo = studentInfoDao{
		internal.NewStudentInfoDao(),
	}
)

// Fill with you ideas below.
