// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"demo3/internal/dao/internal"
)

// internalTeacherInfoDao is internal type for wrapping internal DAO implements.
type internalTeacherInfoDao = *internal.TeacherInfoDao

// teacherInfoDao is the data access object for table teacher_info.
// You can define custom methods on it to extend its functionality as you wish.
type teacherInfoDao struct {
	internalTeacherInfoDao
}

var (
	// TeacherInfo is globally public accessible object for table teacher_info operations.
	TeacherInfo = teacherInfoDao{
		internal.NewTeacherInfoDao(),
	}
)

// Fill with you ideas below.
