// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"demo3/internal/dao/internal"
)

// internalTeacherIsOnDao is internal type for wrapping internal DAO implements.
type internalTeacherIsOnDao = *internal.TeacherIsOnDao

// teacherIsOnDao is the data access object for table teacher_is_on.
// You can define custom methods on it to extend its functionality as you wish.
type teacherIsOnDao struct {
	internalTeacherIsOnDao
}

var (
	// TeacherIsOn is globally public accessible object for table teacher_is_on operations.
	TeacherIsOn = teacherIsOnDao{
		internal.NewTeacherIsOnDao(),
	}
)

// Fill with you ideas below.
