// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"demo3/internal/dao/internal"
)

// internalUserStateDao is internal type for wrapping internal DAO implements.
type internalUserStateDao = *internal.UserStateDao

// userStateDao is the data access object for table user_state.
// You can define custom methods on it to extend its functionality as you wish.
type userStateDao struct {
	internalUserStateDao
}

var (
	// UserState is globally public accessible object for table user_state operations.
	UserState = userStateDao{
		internal.NewUserStateDao(),
	}
)

// Fill with you ideas below.
