// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"demo3/internal/dao/internal"
)

// internalUserDormitoryDao is internal type for wrapping internal DAO implements.
type internalUserDormitoryDao = *internal.UserDormitoryDao

// userDormitoryDao is the data access object for table user_dormitory.
// You can define custom methods on it to extend its functionality as you wish.
type userDormitoryDao struct {
	internalUserDormitoryDao
}

var (
	// UserDormitory is globally public accessible object for table user_dormitory operations.
	UserDormitory = userDormitoryDao{
		internal.NewUserDormitoryDao(),
	}
)

// Fill with you ideas below.
